sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - autoconf
    - bison
    - flex
    - libssl-dev
    - libevent-dev
    - clang
script:
  - autoconf && autoheader
  - ./configure --enable-checking --disable-flto
  - make
  - make cutest && ./cutest
  - (cd tpkg; tar xzf clang-analysis.tpkg; cd clang-analysis.dir; sh clang-analysis.test)
